apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodetodo-deployment
spec:
  selector:
    matchLabels:
      app: nodetodo
  template:
    metadata:
      labels:
        app: nodetodo
    spec:
      containers:
      - name: nodetodo
        image: gcr.io/veerganpatiproject1/nodetodo
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"            
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            port: 3000
            path: /todo
          initialDelaySeconds: 5
          periodSeconds: 2
        readinessProbe:
          httpGet:
            port: 3000
            path: /todo
          initialDelaySeconds: 5
          periodSeconds: 2  
        env:
          - name: MONGO_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: MONGO_DATABASE
            valueFrom:
                configMapKeyRef:
                  name: todo-config  
                  key: database
          - name: DATABASE_SERVICE_NAME
            valueFrom:
                configMapKeyRef:
                  name: todo-config 
                  key: host
        

          
